openapi:
    description: '@project.description@'
    name: ${spring.application.name}
    title: ByggR Archiver
    version: '@project.version@'
resilience4j:
    circuitbreaker:
        instances:
            archive:
                ignoreExceptions: se.sundsvall.dept44.exception.ClientProblem
            messaging:
                ignoreExceptions: se.sundsvall.dept44.exception.ClientProblem
    retry:
        instances:
            archive:
                ignore-exceptions: se.sundsvall.dept44.exception.ClientProblem
            messaging:
                ignore-exceptions: se.sundsvall.dept44.exception.ClientProblem
spring:
    application:
        name: api-byggrarchiver
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
    flyway:
        enabled: false
        baseline-on-migrate: true
logbook:
    body-filters:
        jsonPath:
            - key: '$..file'
              value: '[base64]'
        xPath:
            - key: '//*[contains(local-name(), "filBuffer")]'
              value: '[binary]'
byggrarchiver:
    cron:
        expression: '-'
    shedlock-lock-at-most-for: PT2M
