openapi:
    description: '@project.description@'
    name: ${spring.application.name}
    title: ByggR Archiver
    version: '@project.version@'
resilience4j:
    circuitbreaker:
        instances:
            archive:
                ignoreExceptions: se.sundsvall.dept44.exception.ClientProblem
            messaging:
                ignoreExceptions: se.sundsvall.dept44.exception.ClientProblem
    retry:
        instances:
            archive:
                ignore-exceptions: se.sundsvall.dept44.exception.ClientProblem
            messaging:
                ignore-exceptions: se.sundsvall.dept44.exception.ClientProblem
spring:
    application:
        name: api-byggrarchiver
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
    flyway:
        enabled: false

logbook:
    exclusionfilters:
        jsonPath:
            '$.attachment.file': '[base64]'