version: "3.8"
services:
  ms-archiver-test:
    network_mode: bridge
    container_name: ms-archiver-test
#    logging:
#      driver: "syslog"
#      options:
#        syslog-address: "udp://172.16.254.6:5140"
#        tag: "ms-archiver-test"
    depends_on:
      - ms-archive-wiremock
    restart: always
    image: ms-archiver:test
    ports:
      - 8080:8080
    environment:
      SUNDSVALLS_KOMMUN_INTERNAL_ORIGIN: "https://api-i-test.sundsvall.se"
      SUNDSVALLS_KOMMUN_CONSUMER_KEY: $SUNDSVALLS_KOMMUN_CONSUMER_KEY
      SUNDSVALLS_KOMMUN_CONSUMER_SECRET: $SUNDSVALLS_KOMMUN_CONSUMER_SECRET

      TEMP_ARCHIVE_ORIGIN: ms-archive-wiremock
      WIREMOCK_SERVER_PORT: 8080

      DB_KIND: 'mariadb'
      DB_USERNAME: 'dbuser'
      DB_PWD: 'dbpass'
      DB_URL: 'jdbc:mariadb://ms-archive-mariadb/archiver'
      DB_HIBERNATE_GENERATION: 'drop-and-create'

  ms-archive-mariadb:
    network_mode: bridge
    image: 'mariadb:10.3'
    restart: always
    ports:
      - '3306'
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: 'archiver'
      MYSQL_USER: 'dbuser'
      MYSQL_PASSWORD: 'dbpass'

  ms-archive-wiremock:
    network_mode: bridge
    container_name: ms-archiver-wiremock
    image: wiremock/wiremock
    restart: always
    expose:
      - 8080
    volumes:
      - $PWD/src/test/resources:/home/wiremock