version: "3.8"
services:
  ms-archiver-test:
    network_mode: bridge
    container_name: ms-archiver-test
#    logging:
#      driver: "syslog"
#      options:
#        syslog-address: "udp://172.16.254.6:5140"
#        tag: "ms-archiver-test"
    depends_on:
      - ms-archive-wiremock
    links:
      - ms-archive-wiremock
    restart: always
    image: ms-archiver
    ports:
      - 8080:8080
    environment:
      SUNDSVALLS_KOMMUN_INTERNAL_ORIGIN: "https://api-i-test.sundsvall.se"
      SUNDSVALLS_KOMMUN_CONSUMER_KEY: $SUNDSVALLS_KOMMUN_CONSUMER_KEY
      SUNDSVALLS_KOMMUN_CONSUMER_SECRET: $SUNDSVALLS_KOMMUN_CONSUMER_SECRET

      TEMP_ARCHIVE_ORIGIN: ms-archive-wiremock
      WIREMOCK_SERVER_PORT: 8080

      ARENDEEXPORT_SOAP_ORIGIN: $ARENDEEXPORT_SOAP_ORIGIN
      FBWEBB_ORIGIN: $FBWEBB_ORIGIN
      FB_USER: $FB_USER
      FB_PASSWORD: $FB_PASSWORD

      DB_USERNAME: $DB_USERNAME
      DB_PWD: $DB_PWD
      DB_URL: 'jdbc:mariadb://host.docker.internal:3306/archiver'
      DB_HIBERNATE_GENERATION: 'none'

  ms-archive-wiremock:
    network_mode: bridge
    container_name: ms-archiver-wiremock
    image: wiremock/wiremock
    restart: always
    expose:
      - 8080
    volumes:
      - $PWD/src/test/resources:/home/wiremock

  #  ms-archive-mariadb:
  #    network_mode: bridge
  #    image: 'mariadb:10.3'
  #    restart: always
  #    ports:
  #      - '3306'
  #    environment:
  #      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
  #      MYSQL_DATABASE: 'archiver'
  #      MYSQL_USER: 'dbuser'
  #      MYSQL_PASSWORD: 'dbpass'