openapi: 3.0.1
info:
  title: ByggR Archiver
  description: Application that archives documents from Byggr
  contact: {}
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
  version: "1.1"
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /batch-jobs:
    get:
      tags:
      - byggr-archiver-resource
      operationId: getBatchHistory
      responses:
        "404":
          description: Not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        "500":
          description: Internal Server error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        "400":
          description: Bad request
          content:
            application/problem+json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/Problem'
                - $ref: '#/components/schemas/ConstraintViolationProblem'
        "200":
          description: OK - Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BatchHistoryResponse'
            application/problem+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BatchHistoryResponse'
    post:
      tags:
      - byggr-archiver-resource
      operationId: postBatchJob
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BatchJob'
        required: true
      responses:
        "500":
          description: Internal Server error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        "400":
          description: Bad request
          content:
            application/problem+json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/Problem'
                - $ref: '#/components/schemas/ConstraintViolationProblem'
        "200":
          description: OK - Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchHistoryResponse'
            application/problem+json:
              schema:
                $ref: '#/components/schemas/BatchHistoryResponse'
  /batch-jobs/{batchHistoryId}/rerun:
    post:
      tags:
      - byggr-archiver-resource
      operationId: reRunBatchJob
      parameters:
      - name: batchHistoryId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "404":
          description: Not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        "500":
          description: Internal Server error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        "400":
          description: Bad request
          content:
            application/problem+json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/Problem'
                - $ref: '#/components/schemas/ConstraintViolationProblem'
        "200":
          description: OK - Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchHistoryResponse'
            application/problem+json:
              schema:
                $ref: '#/components/schemas/BatchHistoryResponse'
  /archived/attachments:
    get:
      tags:
      - byggr-archiver-resource
      operationId: getArchiveHistory
      parameters:
      - name: archiveStatus
        in: query
        required: false
        schema:
          type: string
          enum:
          - COMPLETED
          - NOT_COMPLETED
      - name: batchHistoryId
        in: query
        required: false
        schema:
          type: integer
          format: int64
      responses:
        "404":
          description: Not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        "500":
          description: Internal Server error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        "400":
          description: Bad request
          content:
            application/problem+json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/Problem'
                - $ref: '#/components/schemas/ConstraintViolationProblem'
        "200":
          description: OK - Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ArchiveHistoryResponse'
            application/problem+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ArchiveHistoryResponse'
  /api-docs:
    get:
      tags:
      - API
      summary: OpenAPI
      operationId: getApiDocs
      responses:
        "200":
          description: OK
          content:
            application/yaml:
              schema:
                type: string
      x-auth-type: None
      x-throttling-tier: Unlimited
      x-wso2-mutual-ssl: Optional
components:
  schemas:
    BatchJob:
      required:
      - end
      - start
      type: object
      properties:
        start:
          type: string
          description: Startdatum på körningen.
          format: date
          example: 2021-01-01
        end:
          type: string
          description: Slutdatum på körningen.
          format: date
          example: 2021-01-02
    Problem:
      type: object
      properties:
        instance:
          type: string
          format: uri
        type:
          type: string
          format: uri
        parameters:
          type: object
          additionalProperties:
            type: object
        status:
          $ref: '#/components/schemas/StatusType'
        title:
          type: string
        detail:
          type: string
    StatusType:
      type: object
      properties:
        statusCode:
          type: integer
          format: int32
        reasonPhrase:
          type: string
    ConstraintViolationProblem:
      type: object
      properties:
        cause:
          $ref: '#/components/schemas/ThrowableProblem'
        stackTrace:
          type: array
          items:
            type: object
            properties:
              classLoaderName:
                type: string
              moduleName:
                type: string
              moduleVersion:
                type: string
              methodName:
                type: string
              fileName:
                type: string
              lineNumber:
                type: integer
                format: int32
              nativeMethod:
                type: boolean
              className:
                type: string
        type:
          type: string
          format: uri
        status:
          $ref: '#/components/schemas/StatusType'
        violations:
          type: array
          items:
            $ref: '#/components/schemas/Violation'
        title:
          type: string
        message:
          type: string
        instance:
          type: string
          format: uri
        parameters:
          type: object
          additionalProperties:
            type: object
        detail:
          type: string
        suppressed:
          type: array
          items:
            type: object
            properties:
              cause:
                type: object
                properties:
                  stackTrace:
                    type: array
                    items:
                      type: object
                      properties:
                        classLoaderName:
                          type: string
                        moduleName:
                          type: string
                        moduleVersion:
                          type: string
                        methodName:
                          type: string
                        fileName:
                          type: string
                        lineNumber:
                          type: integer
                          format: int32
                        nativeMethod:
                          type: boolean
                        className:
                          type: string
                  message:
                    type: string
                  localizedMessage:
                    type: string
              stackTrace:
                type: array
                items:
                  type: object
                  properties:
                    classLoaderName:
                      type: string
                    moduleName:
                      type: string
                    moduleVersion:
                      type: string
                    methodName:
                      type: string
                    fileName:
                      type: string
                    lineNumber:
                      type: integer
                      format: int32
                    nativeMethod:
                      type: boolean
                    className:
                      type: string
              message:
                type: string
              localizedMessage:
                type: string
        localizedMessage:
          type: string
    ThrowableProblem:
      type: object
      properties:
        cause:
          $ref: '#/components/schemas/ThrowableProblem'
        stackTrace:
          type: array
          items:
            type: object
            properties:
              classLoaderName:
                type: string
              moduleName:
                type: string
              moduleVersion:
                type: string
              methodName:
                type: string
              fileName:
                type: string
              lineNumber:
                type: integer
                format: int32
              nativeMethod:
                type: boolean
              className:
                type: string
        message:
          type: string
        instance:
          type: string
          format: uri
        type:
          type: string
          format: uri
        parameters:
          type: object
          additionalProperties:
            type: object
        status:
          $ref: '#/components/schemas/StatusType'
        title:
          type: string
        detail:
          type: string
        suppressed:
          type: array
          items:
            type: object
            properties:
              cause:
                type: object
                properties:
                  stackTrace:
                    type: array
                    items:
                      type: object
                      properties:
                        classLoaderName:
                          type: string
                        moduleName:
                          type: string
                        moduleVersion:
                          type: string
                        methodName:
                          type: string
                        fileName:
                          type: string
                        lineNumber:
                          type: integer
                          format: int32
                        nativeMethod:
                          type: boolean
                        className:
                          type: string
                  message:
                    type: string
                  localizedMessage:
                    type: string
              stackTrace:
                type: array
                items:
                  type: object
                  properties:
                    classLoaderName:
                      type: string
                    moduleName:
                      type: string
                    moduleVersion:
                      type: string
                    methodName:
                      type: string
                    fileName:
                      type: string
                    lineNumber:
                      type: integer
                      format: int32
                    nativeMethod:
                      type: boolean
                    className:
                      type: string
              message:
                type: string
              localizedMessage:
                type: string
        localizedMessage:
          type: string
    Violation:
      type: object
      properties:
        field:
          type: string
        message:
          type: string
    BatchHistoryResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        start:
          type: string
          format: date
        end:
          type: string
          format: date
        archiveStatus:
          type: string
          enum:
          - COMPLETED
          - NOT_COMPLETED
        batchTrigger:
          type: string
          enum:
          - MANUAL
          - SCHEDULED
        timestamp:
          type: string
          format: date-time
    ArchiveHistoryResponse:
      type: object
      properties:
        documentId:
          type: string
        caseId:
          type: string
        documentName:
          type: string
        documentType:
          type: string
        archiveId:
          type: string
        archiveUrl:
          type: string
        archiveStatus:
          type: string
          enum:
          - COMPLETED
          - NOT_COMPLETED
        timestamp:
          type: string
          format: date-time
        batchHistory:
          $ref: '#/components/schemas/BatchHistoryResponse'
  securitySchemes: {}
